# Generated by Django 4.2.7 on 2023-12-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='reserve',
        ),
    ]
