# Generated by Django 4.1.2 on 2023-10-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_bid_comment_delete_auctionlistings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='current_price',
            new_name='current_bid',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='start_price',
            new_name='start_bid',
        ),
    ]
