# Generated by Django 4.2.7 on 2023-12-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlisting_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
