# Generated by Django 4.1.2 on 2023-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_current_price_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='start_bid',
            new_name='reserve',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
